name: scgip-lab
channels:
  - conda-forge
dependencies:
  - python=3.11
  - scanpy
  - anndata
  - pandas
  - numpy
  - numba<0.65
  - scipy
  - scikit-learn
  - matplotlib
  - pyyaml
  - tqdm
  - jupyter
  - ipykernel
  - seaborn
  - statsmodels
  - pyarrow
  - pip
  - pip:
      - transformers==4.46.*
      - datasets
      - torch
      - accelerate
      - loompy
      - optuna
      - optuna-integration
      - peft
      - tdigest
      - tensorboard
